# CuPy について
* CuPy は、外部インタフェースが NumPy 互換で、内部的に GPU (Cuda) を使っている。
* macOS Sierra 以降では DYLD_LIBRARY_PATH の上書きができなくなったので、Cuda 関連のライブラリを ~/lib などにシンボリックリンクを貼る必要がある
    * /Developer/NVIDIA/CUDA-9.1/lib/ 以下のファイルのシンボリックリンクを ~/lib につくる  
    * 他にも $(HOME)/lib:/usr/local/lib/:/lib/:/usr/lib あたりにシンボリックリンクを作っても良い

In [2]:
import cupy as cp
import numpy as np
a = cp.array([1,2,3,4,5])
b = cp.array([6,7,8,9,10])
c = a + b
print (c)

[ 7  9 11 13 15]


In [3]:
d = cp.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
e = cp.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
f = cp.dot(d,e)
print(f)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Python の list に格納した cupy.ndarray 同士で計算を行う

In [4]:
args = []
rets = []

args.append(cp.array([10,20,30,40,50]))
args.append(cp.array([1,2,3,4,5]))
args.append(cp.array([2,3,4,5,6]))
args.append(cp.array([3,4,5,6,7]))
args.append(cp.array([4,5,6,7,8]))

rets.append(args[0] + args[0])
rets.append(args[0] + args[1])
rets.append(args[0] + args[2])
rets.append(args[0] + args[3])
rets.append(args[0] + args[4])

print(rets[0].get())
print(rets[1].get())
print(rets[2].get())
print(rets[3].get())
print(rets[4].get())


[ 20  40  60  80 100]
[11 22 33 44 55]
[12 23 34 45 56]
[13 24 35 46 57]
[14 25 36 47 58]


# numpy, cupy 両対応のコード

In [5]:
def calc(x, y):
    xp = cp.get_array_module(x)
    return xp.dot(x, y)

x_cpu = np.array([[1,2],[3,4]])
y_cpu = np.array([[5,6],[7,8]])
print(calc(x_cpu, y_cpu))

x_gpu = cp.asanyarray(x_cpu, dtype='float32')
y_gpu = cp.asanyarray(y_cpu, dtype='float32')
print(calc(x_gpu, y_gpu).get())


[[19 22]
 [43 50]]
[[19. 22.]
 [43. 50.]]
